[package]
name="messages_actix"
version="0.1.0"
authors=["YourName<your.name@example.com>"]
edition="2018"

[dependencies]
actix-web="4.0.1"
env_logger="0.9.0"
serde={version="1.0",features=["derive"]}
serde_json="1.0"